"""Airflow DAG generation and injection logic for DQ orchestration."""

from __future__ import annotations

import re
from datetime import datetime, timedelta
from typing import Any, Optional


def generate_consolidated_sp_dag(
    session_id: str,
    sp_name: str,
    dq_project: str,
    dq_dataset: str,
    table_name: str = "",
    schedule: str = "0 6 * * *",
    owner: str = "data-quality",
    alert_email: str = "",
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
    smtp_user: str = "",
    smtp_pass: str = "",
    ingestion_dag_id: str = "",
) -> str:
    stable_id = re.sub(r"[^a-zA-Z0-9_]", "_", table_name).lower() if table_name else session_id[:12]
    dag_id = f"dq_pipeline_{stable_id}"
    ingestion_dag_id = ingestion_dag_id or f"ingestion_{stable_id}"
    generated_at = datetime.utcnow().isoformat()

    return f'''"""
Auto-generated DQ Validation DAG
Session   : {session_id}
Table     : {table_name}
Procedure : {dq_project}.{dq_dataset}.{sp_name}
Generated : {generated_at}Z
DO NOT EDIT MANUALLY — regenerate via the DQ Platform.
"""
from __future__ import annotations

from datetime import timedelta

from airflow.decorators import dag, task
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.utils.dates import days_ago

DAG_ID          = "{dag_id}"
INGESTION_DAG_ID = "{ingestion_dag_id}"
PROJECT         = "{dq_project}"
DQ_DATASET      = "{dq_dataset}"
SP_NAME         = "{sp_name}"
ALERT_EMAIL     = "{alert_email}"
SMTP_HOST       = "{smtp_host}"
SMTP_PORT       = {smtp_port}
SMTP_USER       = "{smtp_user}"
SMTP_PASS       = "{smtp_pass}"

DEFAULT_ARGS = {{
    "owner": "{owner}",
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "depends_on_past": False,
    "email_on_failure": True,
}}


def _send_dq_email_alert(project: str, dq_dataset: str, run_id: str, failed: int = 0, results: list = None) -> None:
    import smtplib
    import logging
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    log = logging.getLogger(__name__)
    if not ALERT_EMAIL or not SMTP_PASS:
        log.warning("Email not configured — skipping alert")
        return

    results = results or []
    rows_html = "".join(
        f"<tr>"
        f"<td style='padding:6px;border:1px solid #dee2e6'>{{r['rule_id']}}</td>"
        f"<td style='padding:6px;border:1px solid #dee2e6'>{{r['rule_type']}}</td>"
        f"<td style='padding:6px;border:1px solid #dee2e6;color:#dc3545;font-weight:bold'>{{r['severity']}}</td>"
        f"<td style='padding:6px;border:1px solid #dee2e6'>{{r.get('observed_value') or 'N/A'}}</td>"
        f"<td style='padding:6px;border:1px solid #dee2e6'>{{r['table_name']}}</td>"
        f"</tr>"
        for r in results
    )

    html = f"""<!DOCTYPE html>
<html>
<body style='font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px'>
    <div style='background:#dc3545;color:white;padding:16px 20px;border-radius:6px 6px 0 0'>
        <h2 style='margin:0'>🚨 Data Quality Alert — FAIL</h2>
    </div>
    <div style='border:1px solid #dee2e6;padding:20px;border-radius:0 0 6px 6px'>
        <h3>DQ Run Complete — {{failed}} failure(s) detected</h3>
        <p>Run ID: <code>{{run_id}}</code></p>
        <p>Stored Procedure: <code>{sp_name}</code></p>
        <p style='color:#dc3545;font-weight:bold'>
            ⚠️ Ingestion pipeline <code>{ingestion_dag_id}</code> has been PAUSED.
        </p>
        <table style='border-collapse:collapse;width:100%;font-size:13px'>
            <thead>
                <tr style='background:#dc3545;color:white'>
                    <th style='padding:8px;text-align:left'>Rule ID</th>
                    <th style='padding:8px;text-align:left'>Type</th>
                    <th style='padding:8px;text-align:left'>Severity</th>
                    <th style='padding:8px;text-align:left'>Observed</th>
                    <th style='padding:8px;text-align:left'>Table</th>
                </tr>
            </thead>
            <tbody>{{rows_html}}</tbody>
        </table>
        <hr style='margin:20px 0'>
        <p style='font-size:12px;color:#6c757d'>
            Generated by Agentic DQ Observability Platform powered by Claude AI.<br>
            Fix the data quality issues and manually unpause the ingestion DAG to resume.
        </p>
    </div>
</body>
</html>"""

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🚨 DQ Alert + Pipeline Blocked — {{failed}} failure(s) | {{run_id}}"
        msg["From"] = SMTP_USER
        msg["To"]   = ALERT_EMAIL
        msg.attach(MIMEText(html, "html"))
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as smtp:
            smtp.ehlo(); smtp.starttls(); smtp.ehlo()
            smtp.login(SMTP_USER, SMTP_PASS)
            smtp.sendmail(SMTP_USER, [ALERT_EMAIL], msg.as_string())
        log.info(f"DQ alert email sent to {{ALERT_EMAIL}} — {{failed}} failures")
    except Exception as exc:
        log.error(f"Failed to send alert email: {{exc}}")


def _pause_ingestion_dag(ingestion_dag_id: str) -> None:
    """Pause the ingestion DAG to stop future runs until manually reviewed."""
    import logging
    log = logging.getLogger(__name__)
    try:
        from airflow.models import DagModel
        from airflow.utils.db import provide_session
        from sqlalchemy.orm import Session

        @provide_session
        def _do_pause(session: Session = None):
            dag_model = session.query(DagModel).filter(
                DagModel.dag_id == ingestion_dag_id
            ).first()
            if dag_model:
                dag_model.is_paused = True
                session.commit()
                log.info(f"Ingestion DAG {{ingestion_dag_id}} paused — manual review required")
            else:
                log.warning(f"Ingestion DAG {{ingestion_dag_id}} not found in Airflow DB")

        _do_pause()
    except Exception as exc:
        log.warning(f"Could not pause ingestion DAG: {{exc}}")


@dag(
    dag_id=DAG_ID,
    default_args=DEFAULT_ARGS,
    description="Consolidated DQ validation — {table_name}",
    schedule_interval="{schedule}",
    start_date=days_ago(1),
    catchup=False,
    max_active_runs=1,
    tags=["data-quality", "dq-platform", "{session_id}"],
)
def dq_pipeline():
    run_dq = BigQueryInsertJobOperator(
        task_id="execute_dq_stored_procedure",
        configuration={{
            "query": {{
                "query": (
                    "CALL `{dq_project}.{dq_dataset}.{sp_name}`"
                    "(\\'{{{{ run_id }}}}\\')"
                ),
                "useLegacySql": False,
            }}
        }},
        project_id=PROJECT,
        gcp_conn_id="google_cloud_default",
    )

    @task(task_id="send_email_alert")
    def send_alert(**context):
        import logging
        from google.cloud import bigquery

        log = logging.getLogger(__name__)
        run_id = context["dag_run"].run_id

        # Query DQ results
        client = bigquery.Client(project=PROJECT)
        query = f"""
            SELECT rule_id, rule_type, severity, status,
                   observed_value, table_name, failure_count
            FROM `{{PROJECT}}.{{DQ_DATASET}}.dq_results`
            WHERE run_id = '{{run_id}}'
              AND status IN ('FAIL', 'ERROR')
            ORDER BY severity DESC
            LIMIT 50
        """.format(PROJECT=PROJECT, DQ_DATASET=DQ_DATASET, run_id=run_id)

        try:
            rows = list(client.query(query).result())
        except Exception as exc:
            log.error(f"Failed to query DQ results: {{exc}}")
            return

        failed = len(rows)
        if failed == 0:
            log.info("No failures — skipping alert")
            return

        results = [
            {{
                "rule_id":        r.rule_id,
                "rule_type":      r.rule_type,
                "severity":       r.severity,
                "observed_value": r.observed_value,
                "table_name":     r.table_name,
            }}
            for r in rows
        ]

        # Check if any CRITICAL (FAIL severity) failures exist
        critical = [r for r in results if r["severity"] == "FAIL"]

        # Always send email alert
        _send_dq_email_alert(
            project=PROJECT,
            dq_dataset=DQ_DATASET,
            run_id=run_id,
            failed=failed,
            results=results,
        )

        # If critical failures — pause ingestion DAG
        if critical:
            log.error(f"{{len(critical)}} CRITICAL failures — pausing ingestion DAG {{INGESTION_DAG_ID}}")
            _pause_ingestion_dag(INGESTION_DAG_ID)
        else:
            log.warning(f"{{failed}} WARN-level failures — ingestion DAG NOT paused (warnings only)")

    run_dq >> send_alert()


dag_instance = dq_pipeline()
'''


def generate_standalone_dag(
    session_id: str,
    rules: list[dict[Any, Any]],
    schedule: str,
    gcp_project: str,
    gcp_dataset: str,
    dq_dataset: str = "dq_observability",
    owner: str = "data-quality",
) -> str:
    dag_id = f"dq_pipeline_{session_id}"
    task_blocks = "\n\n".join(
        _generate_rule_task(rule, gcp_project, gcp_dataset, dq_dataset)
        for rule in rules
    )
    return f'''"""Auto-generated DQ Pipeline DAG — session: {session_id}"""
from __future__ import annotations
from datetime import datetime, timedelta
from airflow.decorators import dag, task_group
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.utils.dates import days_ago
import uuid

DAG_ID = "{dag_id}"
GCP_PROJECT = "{gcp_project}"
GCP_DATASET = "{gcp_dataset}"
DQ_DATASET = "{dq_dataset}"

DEFAULT_ARGS = {{
    "owner": "{owner}",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "depends_on_past": False,
}}

@dag(dag_id=DAG_ID, default_args=DEFAULT_ARGS,
     schedule_interval="{schedule}", start_date=days_ago(1),
     catchup=False, max_active_runs=1)
def dq_pipeline():
    @task_group(group_id="dq_rules_execution")
    def rules_group():
{_indent(task_blocks, 8)}

    rules_group()

dag_instance = dq_pipeline()
'''


def generate_bigquery_check_operator(rule: dict[str, Any]) -> str:
    task_id = _safe_task_id(rule.get("rule_id", "dq_check"))
    sql = (rule.get("generated_sql", "") or "").replace('"', '\\"').replace("\n", " ")
    return f'''    BigQueryCheckOperator(task_id="{task_id}", sql="""{sql}""", use_legacy_sql=False, gcp_conn_id="google_cloud_default")'''


def generate_bigquery_insert_job_operator(rule: dict[str, Any]) -> str:
    task_id = _safe_task_id(rule.get("rule_id", "dq_insert"))
    project = rule.get("project_id", "")
    sql = (rule.get("generated_sql", "") or "").replace('"', '\\"').replace("\n", " ")
    return f'''    BigQueryInsertJobOperator(task_id="{task_id}", configuration={{"query": {{"query": """{sql}""", "useLegacySql": False}}}}, project_id="{project}", gcp_conn_id="google_cloud_default")'''


def inject_task_group_into_dag(dag_file_content, session_id, rules, upstream_task,
                                downstream_task, gcp_project, gcp_dataset, dq_dataset="dq_observability"):
    import re as _re
    task_group_code = _build_task_group_code(session_id, rules, gcp_project, gcp_dataset, dq_dataset)
    injection_marker = f"# DQ_INJECT_POINT:{session_id}"
    if injection_marker in dag_file_content:
        pattern = _re.compile(rf"{_re.escape(injection_marker)}.*?# END_DQ_INJECT:{session_id}", _re.DOTALL)
        dag_file_content = pattern.sub(f"{injection_marker}\n{task_group_code}\n# END_DQ_INJECT:{session_id}", dag_file_content)
    else:
        dag_file_content += f"\n\n{injection_marker}\n{task_group_code}\n# END_DQ_INJECT:{session_id}\n"
    return dag_file_content


def _generate_rule_task(rule, project, dataset, dq_dataset):
    task_id = _safe_task_id(rule.get("rule_id", "dq_rule"))
    rule_name = rule.get("rule_name", task_id)
    severity = rule.get("severity", "WARN")
    sql = (rule.get("generated_sql", f"SELECT 1 -- placeholder for {rule_name}") or "").strip()
    sql_escaped = sql.replace('"""', '\\"\\"\\"').replace("\n", "\\n")
    return f'''        # Rule: {rule_name} | Severity: {severity}
        {task_id}_task = BigQueryInsertJobOperator(
            task_id="{task_id}",
            configuration={{"query": {{"query": """{sql_escaped}""", "useLegacySql": False}}}},
            project_id="{project}", gcp_conn_id="google_cloud_default")'''


def _build_task_group_code(session_id, rules, project, dataset, dq_dataset):
    task_blocks = "\n\n".join(_generate_rule_task(r, project, dataset, dq_dataset) for r in rules)
    return f'''
@task_group(group_id="dq_{session_id[:8]}")
def dq_group_{session_id[:8]}():
{_indent(task_blocks, 4)}
'''


def _safe_task_id(rule_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", rule_id).lower()[:63]


def _indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())
